# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui
import pyqtgraph as pg
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1479, 900)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.colorChooser = QtGui.QComboBox(self.centralwidget)
        self.colorChooser.setGeometry(QtCore.QRect(10, 10, 75, 33))
        self.colorChooser.setObjectName(_fromUtf8("colorChooser"))
        self.colorChooser.addItem(_fromUtf8(""))
        self.colorChooser.addItem(_fromUtf8(""))
        self.colorChooser.addItem(_fromUtf8(""))
        self.colorChooser.addItem(_fromUtf8(""))
        self.colorChooser.addItem(_fromUtf8(""))
        self.colorChooser.addItem(_fromUtf8(""))
        self.colorChooser.addItem(_fromUtf8(""))
        self.typeChooser = QtGui.QComboBox(self.centralwidget)
        self.typeChooser.setGeometry(QtCore.QRect(1210, 10, 75, 33))
        self.typeChooser.setObjectName(_fromUtf8("typeChooser"))
        self.typeChooser.addItem(_fromUtf8(""))
        self.typeChooser.addItem(_fromUtf8(""))
        self.typeChooser.addItem(_fromUtf8(""))
        self.typeChooser.addItem(_fromUtf8(""))
        self.imagesList = QtGui.QListWidget(self.centralwidget)
        self.imagesList.setGeometry(QtCore.QRect(910, 50, 211, 421))
        self.imagesList.setObjectName(_fromUtf8("imagesList"))
        self.deleteContourButton = QtGui.QPushButton(self.centralwidget)
        self.deleteContourButton.setGeometry(QtCore.QRect(1360, 110, 85, 27))
        self.deleteContourButton.setObjectName(_fromUtf8("deleteContourButton"))
        self.saveContourButton = QtGui.QPushButton(self.centralwidget)
        self.saveContourButton.setGeometry(QtCore.QRect(1360, 50, 85, 27))
        self.saveContourButton.setObjectName(_fromUtf8("saveContourButton"))
        self.deleteAllContourButton = QtGui.QPushButton(self.centralwidget)
        self.deleteAllContourButton.setGeometry(QtCore.QRect(1360, 140, 85, 54))
        self.deleteAllContourButton.setObjectName(_fromUtf8(
            "deleteAllContourButton"))
        self.saveAllContourButton = QtGui.QPushButton(self.centralwidget)
        self.saveAllContourButton.setGeometry(QtCore.QRect(1360, 80, 85, 27))
        self.saveAllContourButton.setObjectName(_fromUtf8(
            "saveAllContourButton"))
        self.waterButton = QtGui.QCheckBox(self.centralwidget)
        self.waterButton.setGeometry(QtCore.QRect(550, 830, 101, 22))
        self.waterButton.setObjectName(_fromUtf8("waterButton"))
        self.contourButton = QtGui.QCheckBox(self.centralwidget)
        self.contourButton.setGeometry(QtCore.QRect(170, 830, 101, 22))
        self.contourButton.setObjectName(_fromUtf8("contourButton"))
        self.contoursList = QtGui.QListWidget(self.centralwidget)
        self.contoursList.setGeometry(QtCore.QRect(1140, 50, 211, 421))
        self.contoursList.setObjectName(_fromUtf8("contoursList"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 50, 881, 421))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.topLay = QtGui.QGridLayout(self.gridLayoutWidget)
        self.topLay.setHorizontalSpacing(6)
        self.topLay.setVerticalSpacing(0)
        self.topLay.setObjectName(_fromUtf8("topLay"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 480, 881, 341))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.botLay = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.botLay.setHorizontalSpacing(5)
        self.botLay.setVerticalSpacing(0)
        self.botLay.setObjectName(_fromUtf8("botLay"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1479, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.menuMenu.addAction(self.actionClose)
        self.menuAbout.addAction(self.actionHelp)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.blockSizeSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.blockSizeSpinBox.setGeometry(QtCore.QRect(910, 510, 91, 27))
        self.blockSizeSpinBox.setObjectName(_fromUtf8("blockSizeSpinBox"))
        self.blockSizeLabel = QtGui.QLabel(self.centralwidget)
        self.blockSizeLabel.setGeometry(QtCore.QRect(910, 490, 56, 17))
        self.blockSizeLabel.setObjectName(_fromUtf8("blockSizeLabel"))
        self.methodLabel = QtGui.QLabel(self.centralwidget)
        self.methodLabel.setGeometry(QtCore.QRect(910, 610, 56, 17))
        self.methodLabel.setObjectName(_fromUtf8("methodLabel"))
        self.methodComboBox = QtGui.QComboBox(self.centralwidget)
        self.methodComboBox.setGeometry(QtCore.QRect(910, 630, 75, 33))
        self.methodComboBox.setObjectName(_fromUtf8("methodComboBox"))
        self.methodComboBox.addItem(_fromUtf8(""))
        self.methodComboBox.addItem(_fromUtf8(""))
        self.methodComboBox.addItem(_fromUtf8(""))
        self.offsetSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.offsetSpinBox.setGeometry(QtCore.QRect(910, 570, 91, 27))
        self.offsetSpinBox.setObjectName(_fromUtf8("offsetSpinBox"))
        self.offsetLabel = QtGui.QLabel(self.centralwidget)
        self.offsetLabel.setGeometry(QtCore.QRect(910, 550, 56, 17))
        self.offsetLabel.setObjectName(_fromUtf8("offsetLabel"))
        self.lcdCells = QtGui.QLCDNumber(self.centralwidget)
        self.lcdCells.setGeometry(QtCore.QRect(1290, 510, 64, 23))
        self.lcdCells.setObjectName(_fromUtf8("lcdCells"))
        self.lcdBkgs = QtGui.QLCDNumber(self.centralwidget)
        self.lcdBkgs.setGeometry(QtCore.QRect(1290, 550, 64, 23))
        self.lcdBkgs.setObjectName(_fromUtf8("lcdBkgs"))
        self.lcdRedCells = QtGui.QLCDNumber(self.centralwidget)
        self.lcdRedCells.setGeometry(QtCore.QRect(1290, 590, 64, 23))
        self.lcdRedCells.setObjectName(_fromUtf8("lcdRedCells"))
        self.lcdOthers = QtGui.QLCDNumber(self.centralwidget)
        self.lcdOthers.setGeometry(QtCore.QRect(1290, 630, 64, 23))
        self.lcdOthers.setObjectName(_fromUtf8("lcdOthers"))
        self.cellsCounterLabel = QtGui.QLabel(self.centralwidget)
        self.cellsCounterLabel.setGeometry(QtCore.QRect(1220, 510, 56, 17))
        self.cellsCounterLabel.setObjectName(_fromUtf8("cellsCounterLabel"))
        self.bkgsCounterLabel = QtGui.QLabel(self.centralwidget)
        self.bkgsCounterLabel.setGeometry(QtCore.QRect(1220, 550, 56, 17))
        self.bkgsCounterLabel.setObjectName(_fromUtf8("bkgsCounterLabel"))
        self.redCellsCounterLabel = QtGui.QLabel(self.centralwidget)
        self.redCellsCounterLabel.setGeometry(QtCore.QRect(1220, 590, 56, 17))
        self.redCellsCounterLabel.setObjectName(_fromUtf8("redCellsCounterLabel"))
        self.OthersCounterLabel = QtGui.QLabel(self.centralwidget)
        self.OthersCounterLabel.setGeometry(QtCore.QRect(1220, 630, 56, 17))
        self.OthersCounterLabel.setObjectName(_fromUtf8("OthersCounterLabel"))

        self.mainPlot = pg.PlotWidget()
        self.mainPlot.setAspectLocked()
        self.mainPlot.setMouseEnabled(x=False, y=False)
        self.histogram = pg.HistogramLUTWidget()
        self.roiPlot = pg.PlotWidget()
        self.roiPlot.setAspectLocked()
        self.roiPlot.setMouseEnabled(x=False, y=False)
        self.contourPlot = pg.PlotWidget()
        self.contourPlot.setAspectLocked()
        self.contourPlot.setMouseEnabled(x=False, y=False)
        self.vline = pg.InfiniteLine(angle=90, movable=False)
        self.hline = pg.InfiniteLine(angle=0, movable=False)
        self.roiImage = pg.ImageItem()
        self.roiPlot.addItem(self.roiImage)
        self.contourImage = pg.ImageItem()
        self.contourPlot.addItem(self.contourImage)
        self.contourPlot.addItem(self.vline, ignoreBounds=True)
        self.contourPlot.addItem(self.hline, ignoreBounds=True)

        self.roi = pg.RectROI([100, 100], [100, 100], pen=(0, 9))
        # self.roi.sigRegionChanged.connect(update)

        self.mainPlot.addItem(self.roi)
        self.vb = self.contourImage.getViewBox()

        self.topLay.addWidget(self.mainPlot)
        self.botLay.addWidget(self.histogram, 0, 0)
        self.botLay.addWidget(self.roiPlot, 0, 1, 1, 2)
        self.botLay.addWidget(self.contourPlot, 0, 3, 1, 2)

        self.timer = QtCore.QTimer()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.typeChooser.setItemText(0, _translate("MainWindow", "Cell", None))
        self.typeChooser.setItemText(1, _translate("MainWindow", "Background", None))
        self.typeChooser.setItemText(2, _translate("MainWindow", "Red cell", None))
        self.typeChooser.setItemText(3, _translate("MainWindow", "Other", None))
        self.colorChooser.setItemText(0, _translate("MainWindow", "GRAY", None))
        self.colorChooser.setItemText(1, _translate("MainWindow", "R", None))
        self.colorChooser.setItemText(2, _translate("MainWindow", "G", None))
        self.colorChooser.setItemText(3, _translate("MainWindow", "B", None))
        self.colorChooser.setItemText(4, _translate("MainWindow", "H", None))
        self.colorChooser.setItemText(5, _translate("MainWindow", "S", None))
        self.colorChooser.setItemText(6, _translate("MainWindow", "V", None))
        self.deleteContourButton.setText(_translate(
            "MainWindow", "Delete", None))
        self.saveContourButton.setText(_translate(
            "MainWindow", "Save", None))
        self.deleteAllContourButton.setText(_translate(
            "MainWindow", "Delete All\n(for this img)", None))
        self.saveAllContourButton.setText(_translate(
            "MainWindow", "Save All", None))
        self.waterButton.setText(_translate(
            "MainWindow", "Watershed", None))
        self.contourButton.setText(_translate(
            "MainWindow", "Plot contour", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.blockSizeLabel.setText(_translate("MainWindow", "Block Size", None))
        self.methodLabel.setText(_translate("MainWindow", "Method", None))
        self.methodComboBox.setItemText(0, _translate("MainWindow", "mean", None))
        self.methodComboBox.setItemText(1, _translate("MainWindow", "gaussian", None))
        self.methodComboBox.setItemText(2, _translate("MainWindow", "median", None))
        self.offsetLabel.setText(_translate("MainWindow", "Offset", None))
        self.cellsCounterLabel.setText(_translate("MainWindow", "Cells", None))
        self.bkgsCounterLabel.setText(_translate("MainWindow", "Bkgs", None))
        self.redCellsCounterLabel.setText(_translate("MainWindow", "Red Cells", None))
        self.OthersCounterLabel.setText(_translate("MainWindow", "Others", None))
